thoughtspot/visual-embed-sdk

.github/workflows/main.yml, docs/about-rest-apis.adoc, docs/authentication.adoc, docs/calling-rest-api.adoc, docs/customize-style.adoc, docs/embed-a-viz.adoc, docs/embed-pinboard.adoc, docs/embed-search.adoc, docs/full-embed.adoc, docs/getting-started.adoc, docs/group-api.adoc, docs/index.adoc, docs/metadata-api.adoc, docs/rest-api-reference.adoc, docs/search-data-api.adoc, docs/visual-embed-sdk.adoc
=> Merging doc files from fork

docs/src/asciidocs/demo.adoc, docs/src/asciidocs/writerGuide.adoc, docs/src/pages/doc2.js, docs/src/pages/index.js, docs/src/utils/app-utils.js, docs/src/utils/doc-utils.js, docs/src/utils/lang-utils.js, package-lock.json, package.json, scripts/gatsby-commands.js
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-75674
- example url to test `https://ts-blink.github.io/embed-sdk/en/?link=https://thoughtspot.com&value=dynamic-override`
=> SCAL-75674-param-based-changes-in-docs

docs/src/asciidocs/common/nav.adoc, docs/src/assets/styles/index.scss, docs/src/components/LeftSidebar/index.scss, docs/src/configs/doc-configs.ts, docs/src/pages/index.tsx, docs/src/utils/app-utils.ts
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-77090
=> SCAL-77090-navigation-within-docs

docs/src/pages/index.tsx, docs/src/utils/app-utils.ts
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-77685
=> SCAL-77685-back-button-issue

scripts/gatsby-commands.js
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-79906
- updated default branch name
=> SCAL-79906-new-repo-changes

docs/src/asciidocs/full-embed.adoc
Updated full embed topic to incorporate doc review comments
=> SCAL-78849-doc-review comments

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/configure-saml.adoc, docs/src/asciidocs/customize-actions-menu.adoc, docs/src/asciidocs/customize-style.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/getting-started.adoc, docs/src/asciidocs/index.adoc, docs/src/asciidocs/integration-overview.adoc, docs/src/asciidocs/intro-embed.adoc, docs/src/asciidocs/security-settings.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/trusted-authentication.adoc
Updates for SCAL-79659 and SCAL-80180
=> Tse.apr.cl updates

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/pinboard-export-api.adoc, docs/src/asciidocs/sdk-reference.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/user-api.adoc
- added preview links for playground knobs in embed topics
- Added pinboard export API topic
- Terminology update - Developer Hub to Developer portal
=> Tse apr cl docs

docs/src/asciidocs/spotdev-portal.adoc
Replaced {{tshost}}  with {origin}} in preview links
=> changed tshost prefix to origin in preview links

src/embed/app.spec.ts, src/embed/app.ts
Apply the query params before the hash so that they are persistent with navigation.
=> SCAL-80805

src/embed/app.ts, static/typedoc/classes/appembed.html, static/typedoc/classes/pinboardembed.html, static/typedoc/classes/searchembed.html, static/typedoc/enums/action.html, static/typedoc/enums/authtype.html, static/typedoc/enums/datasourcevisualmode.html, static/typedoc/enums/embedevent.html, static/typedoc/enums/hostevent.html, static/typedoc/enums/page.html, static/typedoc/enums/runtimefilterop.html, static/typedoc/interfaces/appviewconfig.html, static/typedoc/interfaces/embedconfig.html, static/typedoc/interfaces/pinboardviewconfig.html, static/typedoc/interfaces/runtimefilter.html, static/typedoc/interfaces/searchviewconfig.html, static/typedoc/modules.html
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-81067
=> [SCAL-81067] - Added precedence note for path and pageId in fullapp

docs/src/asciidocs/full-embed.adoc, docs/src/configs/doc-configs.js, docs/src/pages/index.tsx
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-81258
=> SCAL-81258-preview-in-playground-url-fixes-testing

docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/integration-overview.adoc, docs/src/asciidocs/spotdev-portal.adoc
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-81198
=> SCAL-81198-preview-in-playground-in-new-tab

docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc
- code snippet update
- error event addition
=> code-snippet clean-up, error event addition

docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/visual-embed-sdk.adoc
Updated xrefs and incorporated review comments
=> Doc link updates

README.md, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/sdk-reference.adoc, docs/src/configs/doc-configs.js, docs/src/utils/app-utils.ts, gatsby-config.js
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-81383
=> SCAL-81383-typedoc-url-changes-based-on-deployment-type

docs/src/components/Search/index.tsx, docs/src/interfaces/index.ts, docs/src/pages/index.tsx, gatsby-config.js
Ticket - https://thoughtspot.atlassian.net/browse/SCAL-81503
=> SCAL-81503-search-removing-params-issue

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/api-auth-session.adoc, docs/src/asciidocs/api-user-group-management.adoc, docs/src/asciidocs/api-user-management.adoc, docs/src/asciidocs/calling-rest-api.adoc, docs/src/asciidocs/configure-saml.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/integration-overview.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/pinboard-export-api.adoc, docs/src/asciidocs/pinboarddata.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/search-data-api.adoc, docs/src/asciidocs/session-api.adoc, docs/src/asciidocs/use-data-api-read.adoc, docs/src/asciidocs/user-api.adoc
Editorial and formatting fixes
=> rest-api-url-update, typo and formatting fixes

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/api-user-group-management.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/pinboard-export-api.adoc, docs/src/asciidocs/rest-api-getstarted.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/tml-api.adoc
- added TML API
- updated text for swagger portal access
- added info on new UI knobs in full app playground screen
- updated full embed params
=> Tse doc updates late changes

docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/spotdev-portal.adoc
* action string and url update
* action-url-update
=> action string and url update (#152)

src/auth.ts, src/config.ts, src/embed/app.ts, src/embed/base.ts, src/embed/pinboard.ts, src/embed/search.ts, src/index.ts, src/types.ts, src/utils.ts
Edited comment text in the typescript files.
=> SCAL-82746 comment-text-edits

docs/src/asciidocs/customize-actions-menu.adoc
Added info about contextual menu
=> custom-action-context menu-update

docs/src/asciidocs/api-changelog.adoc
Added the Changelog topic to list SDK and API changes
=> added api changelog topic

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/api-auth-session.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-rest-api.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/search-data-api.adoc, docs/src/asciidocs/user-api.adoc
- New REST APIs user/updatepreference and metadata/listas
- Note in search data API about the cURL request format
- Nav menu update
=> new-rest-apis and nav menu update

docs/src/components/Search/SearchResult.tsx, docs/src/components/Search/index.tsx, docs/src/interfaces/index.ts, docs/src/pages/index.tsx, gatsby-config.js
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-82972
=> [SCAL-82972]- Handled the html page search functionality by opening the result in new tab

docs/src/components/LeftSidebar/helper.ts, docs/src/components/LeftSidebar/index.tsx
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-83090
=> [SCAL-83090] left panel collapse

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/configure-saml.adoc, docs/src/asciidocs/customize-actions-menu.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/push-data-to-external-app.adoc, docs/src/asciidocs/whats-new.adoc
- Renamed changelog to New features and enhancements and moved it under Release Notes
- In the what's new page, added feature blurbs for SCAL-77342, SCAL-81323, SCAL-81303, SCAL-81293 
- noRedirect edits in embed topics
- Update for SCAL-84732
- custom action doc page edits
=> whats new, SCAL-84732, and noRedirect edits

docs/src/asciidocs/whats-new.adoc
=> href-link-fix

gatsby-config.js
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-85308
=> [SCAL-85308]- Strip links from search strings to avoid href links in search results

docs/src/asciidocs/push-data-to-external-app.adoc, docs/src/asciidocs/whats-new.adoc
Release notes edit
Minor typo fixes
=> final-edits-may-cloud

.github/workflows/deploy.yml
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-85834
=> [SCAL-85834]- Added gatsby-config.js in dev deployment workflow

.github/workflows/deploy.yml, package.json
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-85255
=> [SCAL-85255]- Added multiple script for build and development

src/embed/search.spec.ts, src/embed/search.ts, src/types.ts
https://thoughtspot.atlassian.net/browse/SCAL-85479
=> SCAL-85479 - Add search options parameters in search Embed class.

docs/src/assets/styles/variables.scss, docs/src/components/Document/index.scss
Ticket Id: https://thoughtspot.atlassian.net/browse/SCAL-85625
=> [SCAL-85625] Css updates

docs/src/assets/styles/index.scss, docs/src/assets/styles/variables.scss
Ticket id: https://thoughtspot.atlassian.net/browse/SCAL-85719
=> [SCAL-85719] Add tags for css

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/api-response-pagination.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-rest-api.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/response-pagination.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/security-api.adoc, docs/src/asciidocs/whats-new.adoc
Editorial fixes
Runtime filter updates
=> June cl final updates

docs/src/asciidocs/customize-links.adoc, docs/src/asciidocs/embed-intro.adoc, docs/src/asciidocs/index.adoc, docs/src/asciidocs/intro-embed.adoc
Fixed typo "ThoughSpot" > "ThoughtSpot"
=> typo fixes

src/embed/base.ts, src/mixpanel-service.ts
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-87953
=> Added mix-panel render complete and render error event

src/embed/search.ts, src/types.ts
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-86268
=> [SCAL-86268]- Added expandAllDataSource for search page

docs/src/assets/styles/index.scss, docs/src/assets/styles/variables.scss, docs/src/components/Docmap/index.scss, docs/src/components/Document/index.scss, docs/src/components/LeftSidebar/index.scss
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-87879
=> [SCAL-87879] Changed the links color for dark mode

docs/src/assets/styles/admonition.scss, docs/src/assets/styles/highlight.scss, docs/src/assets/styles/index.scss, docs/src/assets/styles/variables.scss, docs/src/components/Document/index.scss, docs/src/components/Search/index.scss
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-88410
=> [SCAL-88410] css changes

static/typedoc/index.html, static/typedoc/modules.html
=> Scal 82081 large result set for answer

docs/src/assets/styles/index.scss, docs/src/assets/styles/variables.scss
Ticket link -> https://thoughtspot.atlassian.net/browse/SCAL-89459
=> [SCAL-89459]: Added box styles for div

docs/src/components/LeftSidebar/NavContent.tsx, docs/src/components/LeftSidebar/index.scss, docs/src/components/LeftSidebar/index.tsx, docs/src/components/Search/index.scss, src/embed/base.ts
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-89461
=> - Added light/dark mode toggle beside search in mobile view

src/embed/base.ts, src/mixpanel-service.ts, src/utils/processTrigger.ts
Ticket Id: https://thoughtspot.atlassian.net/browse/SCAL-86271
=> [SCAL-86271]- Added reload logic and mixpanel triggers

docs/src/asciidocs/whats-new.adoc, docs/src/components/Dropdown/index.scss, docs/src/components/Dropdown/index.tsx, docs/src/components/Header/index.tsx, docs/src/configs/doc-configs.js, docs/src/pages/index.tsx, src/errors.ts
Ticket Link: https://thoughtspot.atlassian.net/browse/SCAL-89469
=> [SCAL-89469] - Added version dropdown

src/embed/search.ts, src/types.ts
Reverts thoughtspot/visual-embed-sdk#210
TicketId: https://thoughtspot.atlassian.net/browse/SCAL-90104
=> Revert "[SCAL-86268]- Added expandAllDataSource for search page"

docs/src/asciidocs/code-samples.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/home.adoc, docs/src/asciidocs/partials/log-out-api.adoc
- Added a separate page for code samples
- edits to embed topics
- typo fixes
=> July doc updates 4

docs/src/components/Search/SearchResult.tsx, gatsby-config.js
Ticket link: https://thoughtspot.atlassian.net/browse/SCAL-90672
https://thoughtspot.atlassian.net/browse/SCAL-90998
=> [SCAL-90672]- Resolved issue related search

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/api-user-management.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/partials/connection-apis.adoc, docs/src/asciidocs/partials/group-privileges.adoc, docs/src/asciidocs/rest-api-getstarted.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/trusted-authentication.adoc
- REST API content cleanup
- Trusted auth updates
=> rest api content cleanup and auth token updates

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/developer-playground.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/home.adoc, docs/src/asciidocs/trusted-authentication.adoc, docs/src/asciidocs/user-api.adoc
REST API edits to incorporate review comments
Link updates
=> review edits and fixes

docs/src/assets/styles/index.scss, docs/src/components/Header/index.scss, docs/src/components/Header/index.tsx, docs/src/intl/en.json
Ticket Id: https://thoughtspot.atlassian.net/browse/SCAL-92012
=> - Added docs in header to redirect it to home page

docs/src/asciidocs/whats-new.adoc
Changed `July' release instances to to 'August'
=> Changed July instances to August

docs/src/assets/styles/index.scss, docs/src/components/Document/index.scss, docs/src/components/Document/index.tsx, docs/src/pages/index.tsx
Ticket Id: https://thoughtspot.atlassian.net/browse/SCAL-91878
=> [SCAL-91878] - Managed footer css to seperate it out from main content

src/types.ts
Add new flag for hide query details buttons capability
=> [SCAL-83054] Add query details button type to Action

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/customize-email-settings.adoc, docs/src/asciidocs/customize-style.adoc, docs/src/asciidocs/embed-actions.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/home.adoc, docs/src/asciidocs/pinboard-access-control.adoc, docs/src/asciidocs/trusted-authentication.adoc
Doc pages for SCAL-90837 and SCAL-91372
Trusted auth updates
Group API updates
=> Doc updates

docs/src/asciidocs/browser-settings.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/configure-user-access.adoc, docs/src/asciidocs/customize-email-settings.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/intro-embed.adoc, docs/src/asciidocs/partials/group-api-list.adoc, docs/src/asciidocs/pinboard-access-control.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/user-roles.adoc, docs/src/asciidocs/whats-new.adoc
Auth and security article updates
Updates for SCAL-92700
Custom domain URL updates
=> Docs aug cl

docs/src/asciidocs/custom-actions-callback.adoc
Created a whole section to replace the single sentence at the bottom to guide the reader to the code portion where they actually do something with the custom action they create
=> Added paragraph for lead to next page

docs/src/asciidocs/getting-started.adoc
Short descriptions which specify the exact uses and differences between the two types of embed, aimed at users who are new to thoughtspot platform
=> Added description of SearchEmbed and PinboardEmbed

docs/src/asciidocs/browser-settings.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/configure-user-access.adoc, docs/src/asciidocs/custom-actions.adoc, docs/src/asciidocs/custom-domain-configuration.adoc, docs/src/asciidocs/customize-email-settings.adoc
=> Docs custm domain

docs/src/asciidocs/trusted-authentication.adoc
Brough the image of the workflow up higher in the page and added more explanation around what the authenticator server actually does in the workflow
=> Rearranged and additional explanation

src/embed/app.ts, src/types.ts
add a param to store GUIDs of pinboards that need to be hidden
=> [SCAL-92632] hidden pinboards params

docs/src/assets/styles/grid.scss, docs/src/assets/styles/index.scss, docs/src/components/Document/index.scss, docs/src/components/Document/index.tsx, docs/src/components/Footer/index.tsx, docs/src/components/Header/index.tsx, docs/src/configs/doc-configs.js, docs/src/pages/index.tsx
TicketId: https://thoughtspot.atlassian.net/browse/SCAL-92013
=> [SCAL-92013]-css updates

docs/src/components/Breadcrums/index.tsx, docs/src/components/Document/helper.tsx, docs/src/components/Document/index.tsx, docs/src/utils/doc-utils.ts
Tickat Id: https://thoughtspot.atlassian.net/browse/SCAL-94368
=> [SCAL-94368]- Breadcrums improvements

docs/src/asciidocs/about-rest-apis.adoc, docs/src/asciidocs/auth-overview.adoc, docs/src/asciidocs/browser-settings.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/custom-actions.adoc, docs/src/asciidocs/custom-domain-configuration.adoc, docs/src/asciidocs/customization-rebranding.adoc, docs/src/asciidocs/customize-email-settings.adoc, docs/src/asciidocs/developer-playground.adoc, docs/src/asciidocs/home.adoc, docs/src/asciidocs/intro-embed.adoc, docs/src/asciidocs/rest-api-getstarted.adoc, docs/src/asciidocs/security-api.adoc, docs/src/asciidocs/spotdev-portal.adoc, docs/src/asciidocs/visual-embed-sdk.adoc, docs/src/assets/styles/index.scss, docs/src/components/Document/index.scss, docs/src/components/Search/index.scss
Style updates for home page tiles
Left nav updates for breadcrumbs
Custom domain config article update
Typo and editorial fixes
=> Layout updates

docs/src/assets/styles/variables.scss, docs/src/components/Header/index.scss, docs/src/components/Header/index.tsx, docs/src/components/LeftSidebar/helper.tsx
TicketId: https://thoughtspot.atlassian.net/browse/SCAL-94369
=> [SCAL-94369] - Added header link

docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/whats-new.adoc
Updated columnsAndData instances with embedAnswerData 
Updated custom actions block in What's New
=> Code example update

src/embed/ts-embed.ts
https://thoughtspot.atlassian.net/browse/SCAL-94519
=> Added naviage to page function

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/multi-tenancy-best-practices.adoc
Added a new page that gives an overview of best practices to establish mulit-tenancy in ThoughtSpot
=> Bryanthowell ts multitenancy page

src/types.ts
Allow using double click as new interaction
=> New embed event VizPointDoubleClick in types.ts

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-authentication.adoc, docs/src/asciidocs/partials/embed-config.adoc
Added info on getAuthToken() and token validity/expiration
=> Auth token update - SCAL-97582

src/embed/pinboard.ts
Revised the description to remove `iFrame` instance
=> fullHeight description update

docs/src/asciidocs/partials/connection-apis.adoc
Fixed broken cross-references to connection api endpoints
=> fixed broken cross-references

docs/src/asciidocs/rest-api-getstarted.adoc
Added info on user-agent header
Revised the request headers text to improve clarity
=> SCAL-101505-request header update

src/embed/app.ts, src/embed/liveboard.ts, src/embed/ts-embed.ts, src/types.ts
* Updated liveboard instances in comments to Liveboard
* Updated version tags
=> liveboard text updates and version tag changes

src/embed/liveboard.ts, src/types.ts
https://thoughtspot.atlassian.net/browse/SCAL-101584
=> Updated currentRoute & remove hidden for routechange

docs/src/asciidocs/dependency-apis.adoc, docs/src/asciidocs/embed-actions.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/partials/auth-token-api.adoc, docs/src/asciidocs/pinboarddata.adoc, docs/src/asciidocs/security-api.adoc, docs/src/asciidocs/tml-api.adoc, docs/src/asciidocs/user-api.adoc
tml api article update
embed actions list update
minor fixes
=> tml-note and other fixes

docs/src/asciidocs/api-response-pagination.adoc, docs/src/asciidocs/connections-api.adoc, docs/src/asciidocs/dependency-apis.adoc, docs/src/asciidocs/embed-rest-api.adoc, docs/src/asciidocs/group-api.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/pinboarddata.adoc, docs/src/asciidocs/runtime-filters.adoc, docs/src/asciidocs/security-api.adoc, docs/src/asciidocs/terminology-update.adoc, docs/src/asciidocs/tml-api.adoc, docs/src/asciidocs/user-api.adoc, docs/src/asciidocs/whats-new.adoc, src/embed/liveboard.ts
API response code update
LiveboardSnapshot action removal
=> Nov cl docs2

docs/src/asciidocs/terminology-update.adoc
=> Editorial-fixes

docs/src/asciidocs/embed-actions.adoc, docs/src/asciidocs/multi-tenancy-best-practices.adoc, docs/src/asciidocs/partials/custom-action-note.adoc
Minor update to the documentation for hiding and showing actions.
=> Updates to hiding and showing actions

docs/src/asciidocs/whats-new.adoc
=> version heading update

docs/src/asciidocs/admin-api.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/partials/session-api-list.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/search-data-api.adoc, docs/src/asciidocs/session-api.adoc
- session api typo and link fixes
- authorguid param update (metadata api)
- admin api and search data api link fixes
=> api-fixes and authorguid param update

docs/src/asciidocs/partials/metadata-api-list.adoc, docs/src/asciidocs/whats-new.adoc
- `authorguid` param in what's new
=> modified-tag

docs/src/asciidocs/admin-api.adoc, docs/src/asciidocs/code-samples.adoc, docs/src/asciidocs/connections-api.adoc, docs/src/asciidocs/custom-actions-callback.adoc, docs/src/asciidocs/custom-actions-url.adoc, docs/src/asciidocs/customize-actions-menu.adoc, docs/src/asciidocs/developer-playground.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-actions.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/partials/data-connection-apis.adoc, docs/src/asciidocs/partials/metadata-api-list.adoc, docs/src/asciidocs/partials/session-api-list.adoc, docs/src/asciidocs/pinboarddata.adoc, docs/src/asciidocs/push-data-to-external-app.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/search-data-api.adoc, docs/src/asciidocs/security-settings.adoc, docs/src/asciidocs/session-api.adoc, docs/src/asciidocs/user-api.adoc, docs/src/asciidocs/whats-new.adoc
- session api typo and link fixes
- authorguid param update
- admin api and search data api fixes
=> api link fixes and authorguid param update

docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/pinboard-export-api.adoc, docs/src/asciidocs/rest-api-v2-getstarted.adoc, docs/src/asciidocs/rest-api-v2-playground.adoc
=> 8-0-0-cl-edits

docs/src/asciidocs/configure-saml.adoc, docs/src/asciidocs/rest-api-reference.adoc, docs/src/asciidocs/whats-new.adoc
SCAL-100791 updates
Minor edits
=> Late breaking changes

docs/src/asciidocs/security-settings.adoc
Info on including http in the csp URL
=> csp-note-update

src/types.ts
https://thoughtspot.atlassian.net/browse/SCAL-97920
=> [SCAL-97920] Added createMonitor action

docs/src/asciidocs/api-changelog.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/embed-search.adoc, docs/src/asciidocs/full-embed.adoc, docs/src/asciidocs/partials/embed-auth-config.adoc, docs/src/asciidocs/partials/embed-config.adoc, docs/src/asciidocs/rest-api-v1v2-comparison.adoc, docs/src/asciidocs/whats-new.adoc
=> events title update and api list update

README.md, src/embed/base.ts, src/react/index.spec.tsx, src/react/index.tsx, src/react/util.ts
Ability to trigger events on React Components.
=> React Event triggers

docs/src/asciidocs/customize-links.adoc
Text edits for clarifying the embedded link format
=> link-settings-fixes

src/embed/ts-embed.ts
https://thoughtspot.atlassian.net/browse/SCAL-116276
=> Fixed Start & End event in appEmbed/V1Embed

.eslintrc.js, jest.config.sdk.js, package-lock.json, package.json, src/auth.spec.ts, src/auth.ts, src/embed/base.spec.ts, src/embed/base.ts, src/embed/embed.spec.ts, src/embed/ts-embed.spec.ts, src/embed/ts-embed.ts, src/index.ts, src/test/test-utils.ts, src/types.ts, src/utils/authService.spec.ts, src/utils/authService.ts, src/utils/processData.spec.ts, src/utils/processData.ts
See https://docs.google.com/spreadsheets/d/1kTApl2zwK28MVGXgwMBy2S__0siPHP3DVQK1yohlj9E/edit#gid=0 for the case covered.
=> Do not render iframe when login fails

docs/src/asciidocs/api-changelog.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/customize-actions-menu.adoc, docs/src/asciidocs/whats-new.adoc
What's new and changelog update for 8.4.0.cl GA
=> whats new update for 8.4.0.cl

src/embed/liveboard.spec.ts, src/embed/liveboard.ts
https://thoughtspot.atlassian.net/browse/SCAL-123572
=> Embed SDK support for tab configuration options

docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/configure-oidc.adoc, docs/src/asciidocs/connections-api.adoc, docs/src/asciidocs/embed-authentication.adoc, docs/src/asciidocs/intro-embed.adoc, docs/src/asciidocs/rest-api-v2-reference.adoc, docs/src/asciidocs/troubleshooting.adoc, docs/src/assets/styles/variables.scss, docs/src/components/LeftSidebar/index.scss
troubleshooting article addition
=> troubleshooting article update

docs/src/asciidocs/events-ref.adoc
=> SCAL-125331 - events doc update

docs/src/asciidocs/embed-without-sdk.adoc
=> copy link update

src/auth.spec.ts, src/auth.ts, src/utils/authService.spec.ts, src/utils/authService.ts
https://thoughtspot.atlassian.net/browse/SCAL-125593
=> Added new post method for token API

src/embed/app.ts, src/embed/base.ts, src/embed/liveboard.ts, src/embed/search.ts, src/embed/ts-embed.ts, src/types.ts, static/typedoc/classes/AppEmbed.html, static/typedoc/classes/LiveboardEmbed.html, static/typedoc/classes/SearchEmbed.html, static/typedoc/enums/Action.html, static/typedoc/enums/AuthFailureType.html, static/typedoc/enums/AuthStatus.html, static/typedoc/enums/AuthType.html, static/typedoc/enums/DataSourceVisualMode.html, static/typedoc/enums/EmbedEvent.html, static/typedoc/enums/HostEvent.html, static/typedoc/enums/Page.html, static/typedoc/enums/RuntimeFilterOp.html, static/typedoc/interfaces/AppViewConfig.html, static/typedoc/interfaces/EmbedConfig.html, static/typedoc/interfaces/LiveboardViewConfig.html, static/typedoc/interfaces/RuntimeFilter.html, static/typedoc/interfaces/SearchViewConfig.html, static/typedoc/modules.html
Added SW release numbers to the version text
=> SCAL-126101 - Version text update and TypeDoc refresh

docs/src/asciidocs/embed-actions.adoc, docs/src/asciidocs/embed-methods.adoc, docs/src/asciidocs/rel-page-sw.adoc, docs/src/asciidocs/rest-apiv1-changelog.adoc
=> link fixes and editorial checks

docs/src/asciidocs/api-changelog.adoc, docs/src/asciidocs/deprecated-features.adoc, docs/src/asciidocs/rest-api-v1v2-comparison.adoc, docs/src/asciidocs/rest-apiv1-changelog.adoc, docs/src/asciidocs/whats-new.adoc
=> v1-v2-comaprison-update

docs/src/asciidocs/configure-user-access.adoc
Added much more detail in the RLS section, to give a little basic explanation of the types of RLS rules and how they connect to what is in the data warehouse
=> Rls updates

docs/src/asciidocs/api-changelog.adoc, docs/src/asciidocs/common/nav.adoc, docs/src/asciidocs/connections-api.adoc, docs/src/asciidocs/embed-a-viz.adoc, docs/src/asciidocs/embed-pinboard.adoc, docs/src/asciidocs/enable-liveboardv2.adoc, docs/src/asciidocs/events-ref.adoc, docs/src/asciidocs/fixed-issues.adoc, docs/src/asciidocs/getting-started.adoc, docs/src/asciidocs/open-issues.adoc, docs/src/asciidocs/rest-apiv1-changelog.adoc, docs/src/asciidocs/whats-new.adoc
What's new  and change log update
Fixed and known issues addition
Connections API update 
Liveboardv2 update
=> 8 8 0 docs

docs/src/asciidocs/metadata-api.adoc, docs/src/asciidocs/org-api.adoc, docs/src/asciidocs/orgs.adoc, docs/src/asciidocs/session-api.adoc, docs/src/asciidocs/user-api.adoc
=> 8 10 0 docs org

docs/src/asciidocs/api-auth-session.adoc, docs/src/asciidocs/partials/auth-token-api.adoc, docs/src/asciidocs/partials/login-token-api.adoc, docs/src/asciidocs/whats-new.adoc
Cookie info included in session API articles
=> auth updates

src/embed/ts-embed.spec.ts, src/embed/ts-embed.ts, src/types.ts
Flag linkOverride Added to control the Open in a new tab option from embedURL configuration
=> LinkOverride flag added to control open new tab

package.json, src/embed/base.spec.ts, src/types.ts, src/utils/processData.spec.ts, src/utils/processData.ts
Added `ignoreNoCookieAccessAlert` flag to discard the NO_COOKIE_ACCESS error.
=> Added ignore flag for no_cookie_access

src/embed/app.spec.ts, src/embed/app.ts, src/types.ts
Need review added new SDK flag for new modular home page
=> SCAL-167550 Added new SDK flag for new homepage

src/css-variables.ts
Support for Custom CSS in new modular homepage https://thoughtspot.atlassian.net/browse/SCAL-171739
=> SCAL-171739 TSE custome CSS support for new modular homepage

src/embed/app.spec.ts, src/embed/app.ts, src/types.ts
New flag added which only controls the homeapage left nav bar
=> SCAL-171296 Added New SDK flag to control homepageLeftnav

src/embed/ts-embed.spec.ts, src/embed/ts-embed.ts, src/types.ts
=> SCAL-171534 Hide homepage modules from TSE

src/embed/app.spec.ts, src/embed/app.ts
=> SCAL-173256 fixed pageId for new modular home page

src/types.ts
New requirement comes to add support for show/hide query builder button present in homepage left nav bar
=> SCAL-173284 Support hiding query builder from homepage left nav

src/types.ts
Hidden unsupport filter events from typedoc
=> Hidden filter events

src/types.ts
Added 3 new Actions for Watchlist Tse support
1. AddToWatchlist
2. RemoveFromWatchlist
3. CopyKpiLink
=> SCAL-199988 Visual embed SDK changes to add new actions for watchlist

package.json, src/embed/app.ts, src/types.ts
Version info update for homepage controls
=> version update

package.json, src/embed/app.ts, src/types.ts
* version update
* version update
* version bump
* alpha version
* ci check fix
* indentation fix
=> version update (#1096)

src/errors.ts
https://thoughtspot.atlassian.net/browse/SCAL-196825
SCAL -> New provided Message -> "Please select a liveboard to embed."
=> SCAL-196825 Error for Empty LB value ( Removed Pinboard Reference ) 

src/types.ts
Jira: https://thoughtspot.atlassian.net/browse/SCAL-209181
original Issue: https://thoughtspot.atlassian.net/browse/SCAL-208790
PR: https://galaxy.corp.thoughtspot.com/dev/scaligent/pull/9804
=> SCAL-209181 Update the Visual Embed SDK to remove the CopyKpiLink action from the Watchlist

src/types.ts
SCAL-211550 and SCAL-211548 fixes
=> Hostevent doc fixes

src/types.ts
Comment text update for `HostEvent.DownloadAsPDF` and `HostEvent.GetFilters` (Ref SCAL-213495and SCAL-211548)
=> hostevent download pdf and get filters text update

README.md, local/index.html, local/index.ts, package-lock.json, package.json, src/embed/liveboard.spec.ts, src/embed/liveboard.ts, src/embed/ts-embed.spec.ts, src/embed/ts-embed.ts, src/utils/global-styles.ts, src/utils/graphql/preview-service.ts, vite.local.config.ts
This PR adds a capability to show a preview image of a visualization before the visualization renders in the VizEmbed. This helps with percieved performance, the Viz preview is loaded from the Eureka Viz snapshot service.
=> Show preview loader image

src/types.ts
Added examples for action enums
=> Example blocks
