docs/src/components/Docmap/index.scss
docs/src/components/LeftSidebar/index.scss

This PR contains:
- CSS fixes for left and right side panels.

Scal 77285 left panel css fix

---

docs/src/components/BackButton/index.scss
docs/src/components/Button/index.scss
docs/src/components/Docmap/index.scss
docs/src/components/Document/index.scss
docs/src/components/LeftSidebar/index.scss
docs/src/components/Page404/index.scss
docs/src/components/Search/index.scss
docs/src/static/styles/index.scss
docs/src/static/styles/variables.scss

Ticket link -> https://thoughtspot.atlassian.net/browse/SCAL-77375
This PR contains:
- Increased left nav width by 50px.
- Changed font size of the main page to 16px.
- Set the line height to 1.6 for body text in the main page. 
- Added styling for code panels.
- Doc site non-responsive for mobile devices -> As discussed with @ayonghosh  we are not supporting the Mobile view. minimum resolution to support is iPad.
- Removed padding and margin from right side nav and added line height (As per Figma).
- Added styles for the bottom most <a> tag (id="preview-in-playground") on document to look like a button.

[SCAL-77375] UI polishing fixes

---

docs/src/components/Document/index.scss
docs/src/static/styles/variables.scss

This PR contains:
- Styling for table in document.
- Styling for all the code blocks.
- Code language display on hover over code block (was static before).
Here is the screenshot:

[SCAL-77688] - Added styling for table in doc

---

docs/src/assets/styles/index.scss
docs/src/components/LeftSidebar/index.scss
docs/src/components/LeftSidebar/index.tsx
docs/src/constants/uiContants.ts
docs/src/pages/index.tsx
docs/src/utils/app-utils.ts
package-lock.json
package.json

Ticket link -> https://thoughtspot.atlassian.net/browse/SCAL-77546
This PR contains:
- Left nav resizable functionality.
Here is a demo:
https://user-images.githubusercontent.com/78337774/108967126-1d687b00-76a5-11eb-9c82-f8de22d9bb47.mp4

[SCAL-77546] - Added left nav resizable functionality

---

docs/src/asciidocs/about-rest-apis.adoc
docs/src/asciidocs/api-auth-session.adoc
docs/src/asciidocs/api-user-group-management.adoc
docs/src/asciidocs/calling-rest-api.adoc
docs/src/asciidocs/common/nav.adoc
docs/src/asciidocs/custom-actions-viz.adoc
docs/src/asciidocs/embed-pinboard.adoc
docs/src/asciidocs/embed-rest-api.adoc
docs/src/asciidocs/full-embed.adoc
docs/src/asciidocs/group-api.adoc
docs/src/asciidocs/metadata-api.adoc
docs/src/asciidocs/pinboard-export-api.adoc
docs/src/asciidocs/pinboarddata.adoc
docs/src/asciidocs/rest-api-getstarted.adoc
docs/src/asciidocs/rest-api-reference.adoc
docs/src/asciidocs/search-data-api.adoc
docs/src/asciidocs/security-api.adoc
docs/src/asciidocs/session-api.adoc
docs/src/asciidocs/spotdev-portal.adoc
docs/src/asciidocs/tml-api.adoc
docs/src/asciidocs/user-api.adoc
docs/src/asciidocs/whats-new.adoc

Added doc pages for new REST APIs (metadata apis and session apis)
Revised the intro section to provide more information about request headers, content-type etc.
Fixes for tickets in the SCAL-84298 epic
Editorial fixes

REST API doc updates

---

docs/src/constants/uiConstants.ts

Ticket link -> https://thoughtspot.atlassian.net/browse/SCAL-87892

[SCAL-87892]: Fixed hiding of anchor target/content

---

docs/src/asciidocs/partials/login-token-api.adoc
docs/src/assets/styles/variables.scss
docs/src/components/Document/index.scss

- added the `overflow: auto;` attribute to the `.documentWrapper pre` style
- changed the tag font size to 14 px
- fixed typos

typo-fixes and css updates

---

docs/src/asciidocs/embed-authentication.adoc

Deleted one character of whitespace to reformat the JavaScript example. This is mainly just a test of the process of pull requests

Whitespace change in code example

---

docs/src/asciidocs/group-api.adoc
docs/src/asciidocs/user-api.adoc

Fixed typos in the user and group api articles

typo-fixes

---

docs/src/components/Docmap/index.tsx

ticketId: https://github.com/thoughtspot/visual-embed-sdk/pull/261

SCAL-91428-Fixed right side nav disappears issue

---

src/embed/search.ts
src/types.ts

If set to true, all filter chips from a pinboard page will be read-only (no X buttons)

[SCAL-92387] add filter removal param

---

docs/src/asciidocs/embed-actions.adoc

I moved the explanatory portion to the start, with the list of all the actions below - was a near straight copy / paste from existing content

Re-ordered the page

---

docs/src/asciidocs/embed-search.adoc

Current documentation assumes npm / node.js install. Adding the form for non-NPM installs as well

Added reference to ES6 import

---

docs/src/asciidocs/code-samples.adoc

Added a commented out ES6 import for people not using npm

Updated to add ES6 imports

---

docs/src/asciidocs/code-samples.adoc

Updated the name on the REST API / TML library and added ts_everywhere_resources

Added links

---

docs/src/asciidocs/common/nav.adoc
docs/src/assets/styles/variables.scss
docs/src/components/Breadcrums/index.scss
docs/src/components/Breadcrums/index.tsx
docs/src/components/Document/index.scss
docs/src/components/Document/index.tsx
docs/src/components/Search/index.tsx
docs/src/pages/index.tsx
docs/src/utils/doc-utils.ts

Ticke Id: https://thoughtspot.atlassian.net/browse/SCAL-92011

[SCAL-92011] - Added breadcrums depends on routes change

---

docs/src/assets/styles/variables.scss
docs/src/components/Breadcrums/index.scss

TicketId: https://thoughtspot.atlassian.net/browse/SCAL-94080

[SCAL-94080]- Updated breadcrums style

---

docs/src/asciidocs/tml-api.adoc

There was an extra square bracket and parenthesis that was incorrect in the example. I also changed the guid property of the second element since it was an exact repeat of the first one, to remove confusion

Corrected error in import_objects format

---

docs/src/asciidocs/tml-api.adoc

Question arose around whether you can specify the GUID for a newly created TML object. Testing showed that the system always generates a new guid. Clarified just slightly and formatted the explanation of force_create a little more.

Update to clarify rules around new GUIDs

---

docs/src/asciidocs/search-data-api.adoc

en-US is required for this API to work, added basic JavaScript example of how to configure for a REST call within the browser to send that header, per JIRA SCAL-87059

Added JavaScript examples of Accept-Language

---

docs/src/asciidocs/metadata-api.adoc

Since this is a customer-facing error, can we merge into the next release ASAP and also backport to get it corrected in production? Martha Miller had a customer failing when attempting to implement the metadata/listobjectheaders endpoint from this documentation. Current release version does not show that the 'subtypes' argument needs to be a JSON array (even in Swagger, it only says 'list of' as the hint). I've updated the documentation to mention the JSON array and updated the cURL and URL examples.

Documentation of metadata/listobjectheaders for sub-type was incorrect

---

docs/src/asciidocs/pinboarddata.adoc

This REST API supports runtime filters but the documentation of that feature is in the main cloud-docs and would be difficult to find. Added direct link (and fixed a section header to be sentence case per style guidelines)

Added info about runtime filters

---

docs/src/asciidocs/multi-tenancy-best-practices.adoc

Share with all can also share to groups they don't belong in.

Adding clarification for sharing privileges.

---

docs/src/configs/doc-configs.js
gatsby-config.js
package.json

For Algolia federated search, we need to provide a sitemap file.
Added 'gatsby-plugin-sitemap' plugin to generate XML file for all the pageId's
current URL format:  https://developers.thoughtspot.com/docs/?pageid={pageID}
the XML file can be accessed from {docs-url}/sitemap/sitemap-0.xml in production

Sitemap docs

---

README.md
src/embed/app.ts
src/embed/pinboard.ts

Pointing links to the developers.thoughtspot.com/docs site

Updated SDK reference link

---

docs/src/asciidocs/security-api.adoc
docs/src/asciidocs/whats-new.adoc

Fixed the broken link in What's New page

Fixed broken link

---

docs/src/asciidocs/api-auth-session.adoc

Customers were asking questions on how the login actually works in browser vs. not. Expanded entry paragraph here to make it clear

Added clarification on sessions and REST API

---

docs/src/asciidocs/catalog-and-audit.adoc

Don't know where this should go in the menu system, possibly under "REST API fundamentals".

Catalog and audit documentation

---

docs/src/asciidocs/common/nav.adoc

Added Catalog and audit article to the left nav menu

added catalog and audit article to the left nav

---

docs/src/asciidocs/security-settings.adoc

Protocol exclusion in CSP entries

---

docs/src/asciidocs/code-samples.adoc
docs/src/asciidocs/common/nav.adoc
docs/src/asciidocs/database-api.adoc
docs/src/asciidocs/embed-actions.adoc
docs/src/asciidocs/metadata-api.adoc
docs/src/asciidocs/partials/database-api-list.adoc
docs/src/asciidocs/partials/group-api-list.adoc
docs/src/asciidocs/pinboard-export-api.adoc
docs/src/asciidocs/rest-api-reference.adoc
docs/src/asciidocs/security-settings.adoc
docs/src/asciidocs/spotdev-portal.adoc
docs/src/assets/styles/variables.scss
docs/src/components/BackButton/index.scss
docs/src/components/Document/index.scss
docs/src/components/LeftSidebar/index.scss
docs/src/intl/en.json

- Database APIs - SCAL-107762
- Design changes - SCAL-105048

database apis and design changes

---

docs/src/asciidocs/common/nav.adoc
docs/src/asciidocs/embed-authentication.adoc
docs/src/asciidocs/rest-api-v1v2-comparison.adoc
docs/src/asciidocs/security-settings.adoc
docs/src/assets/styles/variables.scss
docs/src/components/BackButton/index.scss
docs/src/components/Document/index.scss
docs/src/components/LeftSidebar/index.scss

- CSP fixes (SCAL-107421)
- CSS fixes SCAL-105048

Csp and css fixes

---

docs/src/asciidocs/api-changelog.adoc
docs/src/asciidocs/embed-a-viz.adoc
docs/src/asciidocs/embed-events.adoc
docs/src/asciidocs/embed-pinboard.adoc
docs/src/asciidocs/embed-search.adoc
docs/src/asciidocs/full-embed.adoc
docs/src/asciidocs/rest-api-v1v2-comparison.adoc
docs/src/asciidocs/whats-new.adoc

Events title update
API list fixes

api list update and events title update

---

docs/src/asciidocs/embed-actions.adoc

Updated description for TML UI actions

tml-action-fixes

---

src/types.ts

https://thoughtspot.atlassian.net/browse/SCAL-112885

SCAL-112928: Hide Redundant Embed Actions

---

docs/src/asciidocs/common/nav.adoc
docs/src/asciidocs/custom-actions-callback.adoc
docs/src/asciidocs/custom-actions-url.adoc
docs/src/asciidocs/custom-actions.adoc
docs/src/asciidocs/customize-actions-menu.adoc
docs/src/asciidocs/whats-new.adoc

Commented out all app action and send-to-slack content in 8.1.0 docs

app actions and slack update removal

---

src/embed/events.spec.ts
src/embed/ts-embed.ts
src/types.ts

This provides a way to listen to all events emitted from an embed, without enumerating each and every event listener.

ALL event type

---

docs/src/asciidocs/api-changelog.adoc
docs/src/asciidocs/embed-a-viz.adoc
docs/src/asciidocs/embed-authentication.adoc
docs/src/asciidocs/embed-pinboard.adoc
docs/src/asciidocs/embed-search.adoc
docs/src/asciidocs/embed-without-sdk.adoc
docs/src/asciidocs/full-embed.adoc
docs/src/asciidocs/group-api.adoc
docs/src/asciidocs/partials/embed-config.adoc
docs/src/asciidocs/partials/tml-api-list.adoc
docs/src/asciidocs/rest-api-v2.adoc
docs/src/asciidocs/rest-apiv1-changelog.adoc
docs/src/asciidocs/security-api.adoc
docs/src/asciidocs/whats-new.adoc

What's new and changelog updates
SCAL-119202 fix
Minor edits and link fixes

8 3 0.cl GA version

---

package.json
src/react/index.tsx

Use deep comparison instead of ref comparison useEffect dependency to prevent unnecessary re-render

Fix ThoughtSpot react component re-render issues

---

src/embed/ts-embed.ts

Adding undefined return type on the index type as width and height are optional on the FrameParams interface. This is otherwise causing issues in Angular builds

FrameParams interface declaration

---

docs/src/asciidocs/embed-search.adoc
docs/src/asciidocs/whats-new.adoc

SCAL-120656/SCAL-119082 SearchEmbed beta alert update

update for SCAL-120656/SCAL-119082

---

docs/src/asciidocs/code-samples.adoc
src/auth.spec.ts
src/auth.ts
src/config.spec.ts
src/types.ts

Issue: https://github.com/thoughtspot/visual-embed-sdk/issues/679
https://thoughtspot.atlassian.net/browse/SCAL-122670

Added SAML Auth Type

---

docs/src/asciidocs/api-changelog.adoc
docs/src/asciidocs/common/nav.adoc
docs/src/asciidocs/database-api.adoc
docs/src/asciidocs/developer-playground.adoc
docs/src/asciidocs/embed-events.adoc
docs/src/asciidocs/full-embed.adoc
docs/src/asciidocs/logs-api.adoc
docs/src/asciidocs/rest-api-reference.adoc
docs/src/asciidocs/rest-api-v2-reference.adoc
docs/src/asciidocs/runtime-filters.adoc
docs/src/asciidocs/whats-new.adoc

What's new and changelog update for the upcoming release (8.5.0.cl)

8-5-0-whats-new publication

---

src/types.ts

Updated Host events and Embed events enum to reflect the additions in events.

SCAL-123538: Update Host events and Embed events enum

---

docs/src/asciidocs/trusted-authentication.adoc

Rework of trusted auth to reflect the conversations I've been having with customers lately - much more clarity around front-end, back-end separation, what parts they must do and what needs to happen to be secure, and additional REST API command for user management and authentication at the sign-in time. I anticipate we'll do another update at some point to add in more examples or code based on this full workflow

Trusted auth updates 2

---

docs/src/asciidocs/api-auth-session.adoc
docs/src/asciidocs/custom-viz-rest-api.adoc

Added in examples in using the REST API from the browser using the more modern Fetch / Promises pattern which Bill uses in his examples. There are numerous benefits to showing this pattern. All of it is based on the existing examples which I have also left in the documentation there.

Fetch examples

---

src/embed/liveboard.ts
static/typedoc/classes/AppEmbed.html
static/typedoc/classes/LiveboardEmbed.html
static/typedoc/classes/SearchEmbed.html
static/typedoc/enums/Action.html
static/typedoc/enums/AuthFailureType.html
static/typedoc/enums/AuthStatus.html
static/typedoc/enums/AuthType.html
static/typedoc/enums/DataSourceVisualMode.html
static/typedoc/enums/EmbedEvent.html
static/typedoc/enums/HostEvent.html
static/typedoc/enums/Page.html
static/typedoc/enums/RuntimeFilterOp.html
static/typedoc/interfaces/AppViewConfig.html
static/typedoc/interfaces/EmbedConfig.html
static/typedoc/interfaces/LiveboardViewConfig.html
static/typedoc/interfaces/RuntimeFilter.html
static/typedoc/interfaces/SearchViewConfig.html
static/typedoc/modules.html

Added deprecated tag to enableVizTranformations in the SDK docs. This attribute has also been removed from the developer docs in the upcoming [8.8.0 version](https://developers.thoughtspot.com/docs/?pageid=embed-sdk-changelog).

SCAL-131371  enableVizTranformations param update

---

docs/src/asciidocs/embed-pinboard.adoc

There's a missing comma after the value for key visibleVizs in this [file](https://github.com/thoughtspot/visual-embed-sdk/blob/38cce8ab8ca771310dec0e7252bae81487bfde2f/docs/src/asciidocs/embed-pinboard.adoc), came across the error using your [docs](https://my1.thoughtspot.cloud/#/develop/documentation/en/?pageid=embed-liveboard) to embed a liveboard.

fix: add missing comma after pair in object (#791)

---

src/auth.ts
src/embed/liveboard.ts
src/embed/search.spec.ts
src/embed/search.ts
src/embed/ts-embed.spec.ts
src/embed/ts-embed.ts
src/types.ts
src/utils/processData.ts

- Remove iframe and show Not logged in message if token fetch fails during app_init
- Remove iframe and show Not logged in message if update token fails during auth expiry
- Remove all TS iframes and show Not logged in message if logout SDK function is called
- Added `HideSearchBar` param

SCAL-183676 SCAL-186974 Remove embedded content when token fetch fails or logout is called

---

src/embed/app.spec.ts
src/embed/liveboard.spec.ts
src/embed/pinboard.spec.ts
src/embed/search.spec.ts
src/embed/search.ts
src/embed/ts-embed.spec.ts
src/embed/ts-embed.ts
src/react/index.spec.tsx
src/types.ts

- make excludeRuntimeFiltersfromURL true by default
- unhide it from jsdocs and add description
- Tests modified to include runtime filters in url only when excludeRuntimeFiltersfromURL is false.
- Test added to check runtime filters should not be part of URL when excludeRuntimeFiltersfromURL is not defined by user
- Test added to check runtime filters should be part of app_init cb payload when excludeRuntimeFiltersfromURL is not defined by user

SCAL-178305 : make excludeRuntimeFiltersfromURL true by default, unhide it from jsdocs and add description

---

src/embed/app.ts
src/embed/search.spec.ts
src/embed/search.ts
src/react/index.spec.tsx
src/types.ts

This flag controls the behavior of the search bar. If this flag is set to true, the saved-answer will open with the search bar collapsed initially to give more space for the visualization in the answer.

[SCAL-203325] Add collapseSearchBarInitially flag

---

src/types.ts

If it were `ManageMonitor` it would also be encoded as such in query parameter. This would cause a mismatch while comparing it in Blink, partially causing the bug SCAL-216965

SCAL-216965 Change enum representation to camel-case
